name: Deploy Latest Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  Default:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out Repo 
        uses: actions/checkout@v4
      -
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - 
        run: 'npm install'
      -
        run: 'npm run docs:build'
      - 
        name: Deploy to Web server
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          SOURCE: .vitepress/dist/
